### PR TITLE
Prevent signer runs over inactive logs

### LINKED ISSUE #1283: Signer tries to perform sequencing passes on frozen logs
The signer gets PermissionDenied errors as a result of the log being in state "FROZEN", which are subsequently logged and recorded as failed signing runs. Instead, the signer should skip sequencing for frozen trees.

An example of the error being logged, as seen during TestLiveLifecycleCTIntegration:
```
E0913 11:56:11.820802   21972 log_operation_manager.go:399] ExecutePass(973127127382877204) failed: error retrieving log 973127127382877204: rpc error: code = PermissionDenied desc = operation: SequenceLog not allowed for tree type: LOG state: FROZEN
```

### PR DESCRIPTION
**Pull request by pavelkalinnikov**
Signer tries to process all logs that it holds mastership for. This
change refactors it so that only active (i.e. not deleted or FROZEN)
logs of those are taken into consideration. This prevents signer
producing a sustaining stream of errors saying that it's unable to
sequence logs that are in fact inactive.

Fixes #1283

### CODE REVIEW

File: server/log_operation_manager.go [hunk 1]
```diff
@@ -224,7 +224,14 @@ func (l *LogOperationManager) masterFor(ctx context.Context, allIDs []int64) ([]
 
 	held := l.tracker.Held()
 	heldIDs := make([]int64, 0, len(allIDs))
+	sort.Strings(allStringIDs)
 	for _, s := range held {
```
Comment (pavelkalinnikov) [inline server/log_operation_manager.go]: Looks like the "active as master for N/M" message below compares chickens to tables.

Comment (RJPercival) [reply server/log_operation_manager.go]: Haha I was going to mention that, but since this change doesn't actually resign mastership of the frozen/deleted trees, it seemed a bit out of scope. Come to think of it though, `len(allIDs)` will decrease when a tree is frozen/deleted, but `len(held)` won't, will it? That would probably be confusing.

Comment (pavelkalinnikov) [reply server/log_operation_manager.go]: Dome some logging/commenting rearrangement. PTAL.

**Comment by pavelkalinnikov** [comment]
Ping

**Comment by pavelkalinnikov** [comment]
Rob is OOO. David, could you PTAL?

File: server/log_operation_manager.go [hunk 2]
```diff
@@ -224,43 +228,53 @@ func (l *LogOperationManager) masterFor(ctx context.Context, allIDs []int64) ([]
...
 		l.lastHeld = make([]int64, len(logIDs))
 		copy(l.lastHeld, logIDs)
-		heldInfo := l.heldInfo(ctx, logIDs)
-		glog.Infof("now acting as master for %d / %d, %s", len(logIDs), len(allIDs), heldInfo)
+		glog.Info(msg)
 		if l.info.Registry.SetProcessStatus != nil {
 			l.info.Registry.SetProcessStatus(heldInfo)
 		}
 	}
+	glog.V(1).Info(msg)
```
Comment (daviddrysdale) [inline server/log_operation_manager.go]: maybe put this in an `} else {` so there's not double-logging with `-v 1` ?

File: server/log_operation_manager.go [hunk 3]
```diff
@@ -224,43 +228,53 @@ func (l *LogOperationManager) masterFor(ctx context.Context, allIDs []int64) ([]
...
+	activeIDs, err := l.getActiveLogIDs(ctx)
 	if err != nil {
-		return fmt.Errorf("failed to retrieve full list of log IDs: %v", err)
+		return fmt.Errorf("failed to list active log IDs: %v", err)
 	}
-	logIDs, err := l.masterFor(ctx, allIDs)
+	// Skip IDs of the logs that are not active (for example, deleted or FROZEN
+	// ones). Note that we might still hold mastership for some of them.
+	// TODO(pavelkalinnikov): Resign mastership for the inactive logs.
+	logIDs, err := l.masterFor(ctx, activeIDs)
```
Comment (daviddrysdale) [inline server/log_operation_manager.go]: The comment describes the secondary function of the call to `masterFor` rather than its primary purpose. Maybe `// Find the logs we are master for, skipping those logs that are not active...` or somesuch
