### PR TITLE
Run all the tests in the presubmit scripts

### LINKED ISSUE #1850: Travis doesn't run "go test" without the short flag
`go test github.com/google/trillian/quota/etcd/quotaapi`

This test command reliably fails for me. It doesn't on Travis. Looking into why, it's because Travis doesn't run the TestServer_UpdateConfig_Race test because we always provide the short test flag.

### PR DESCRIPTION
**Pull request by mhutchinson**
This script is invoked by Travis and by good developers that want to ensure their changes work properly. Only running those tests that don't self identify as not short doesn't work well for either of these use cases. This fixes #1850 .

### CODE REVIEW

File: scripts/presubmit.sh [hunk 1]
```diff
@@ -87,7 +87,7 @@ main() {
     echo 'running go build'
     go build ./...
 
-    export TEST_FLAGS="-short -timeout=${GO_TEST_TIMEOUT:-5m}"
+    export TEST_FLAGS="-timeout=${GO_TEST_TIMEOUT:-5m}"
```
Comment (RJPercival) [inline scripts/presubmit.sh]: It might be useful to be able to supplement these flags from outside of the script, e.g.
```suggestion
    export TEST_FLAGS="${TEST_FLAGS} -timeout=${GO_TEST_TIMEOUT:-5m}"
```

Comment (RJPercival) [reply scripts/presubmit.sh]: That might be best done as a separate change though, and would call for a CHANGELOG entry since there's a chance someone already has that environment variable set and it suddenly starts interacting with this script.

Comment (mhutchinson) [reply scripts/presubmit.sh]: Will leave as-is. If anyone wants this feature they can add it. It's orthogonal to the thrust of this PR.

Comment (RJPercival) [reply scripts/presubmit.sh]: The relevance was that it'd allow people to keep running the tests with the -short flag if they so desired.
