### PR TITLE
Convert extension.Registry to a simple struct

### LINKED ISSUE #416: Fix MySQL storage statement leak
Might possibly be only in my branch but needs investigating. Occurred after about 14.5M leaves sequenced. It's a server global setting so could be in any code that interacts with prepared statements.

```
W0307 08:33:03.287471    7153 sequencer.go:170] 0: Sequencer failed to start tx: failed to get tree row for treeID 
0: Error 1461: Can't create more than max_prepared_stmt_count statements (current value: 16382)
W0307 08:33:03.287493    7153 sequencer_manager.go:110] 0: Error trying to sequence batch for: failed to get tree r
ow for treeID 0: Error 1461: Can't create more than max_prepared_stmt_count statements (current value: 16382)
W0307 08:33:03.389171    7153 sequencer.go:170] 0: Sequencer failed to start tx: failed to get tree row for treeID 
0: Error 1461: Can't create more than max_prepared_stmt_count statements (current value: 16382)
W0307 08:33:03.389193    7153 sequencer_manager.go:110] 0: Error trying to sequence batch for: failed to get tree r
ow for treeID 0: Error 1461: Can't create more than max_prepared_stmt_count statements (current value: 16382)
```

### PR DESCRIPTION
**Pull request by RJPercival**
Builds upon #434 - please review that first.

extension.Registry has been changed from an interface to a struct. There is no longer any need for a MockRegistry. Most of the `extension.builtin` package has been deleted as it is unnecessary - only the MySQL setup code remains, and this too should probably either be deleted or moved to a more appropriate place.

Because `builtin.defaultRegistry` no longer exists, `builtin.keyProvider` has moved to `keys.PEMKeyProvider`.

Fixes #416.

### CODE REVIEW

File: extension/builtin/default_registry.go [hunk 1]
```diff
@@ -36,62 +29,20 @@ var (
 	MySQLURIFlag = flag.String("mysql_uri", "test:zaphod@tcp(127.0.0.1:3306)/test", "uri to use with mysql storage")
 )
 
-// Default implementation of extension.Registry.
-type defaultRegistry struct {
-	db *sql.DB
+// UseSQLDB configures the registry to use the given SQL database for all storage.
+func UseSQLDB(r *extension.Registry, db *sql.DB) {
```
Comment (gdbelvin) [inline extension/builtin/default_registry.go]: Would it be possible to convert these `Use*` functions to `New*` functions? 
For example, this function modifies the given registry which could be surprising for the caller.
Could this be a NewFromDB which returned a new registry that's populated in the way you suggest here?

Comment (codingllama) [inline extension/builtin/default_registry.go]: +1 for `New*`.

In fact, I'd be tempted to either delete UseSQLDB entirely or move it to a testonly package. I don't see it getting used for non-test code.

File: extension/builtin/default_registry.go [hunk 2]
```diff
@@ -36,62 +29,20 @@ var (
...
-func NewExtensionRegistry(db *sql.DB) (extension.Registry, error) {
-	return &defaultRegistry{db: db}, nil
-}
-
-// NewDefaultExtensionRegistry returns the default extension.Registry implementation, which is
-// backed by a MySQL database and configured via flags.
-// It supports loading private keys from PEM files.
-func NewDefaultExtensionRegistry() (extension.Registry, error) {
+// UseMySQLDBSetByFlags configures the registry to use the MySQL database specified by the --mysql_uri flag for all storage.
+func UseMySQLDBSetByFlags(r *extension.Registry) error {
```
Comment (codingllama) [inline extension/builtin/default_registry.go]: Rename to NewRegistryFromFlags? So if it evolves to use other flags the name still stands.

I'd also suggest returning a complete registry here (keys.Provider included).

File: extension/builtin/default_registry.go [hunk 3]
```diff
@@ -36,62 +29,20 @@ var (
...
 	db, err := mysql.OpenDB(*MySQLURIFlag)
```
Comment (codingllama) [inline extension/builtin/default_registry.go]: Food for thought: because we create the DB object inside this func, and the registry then takes indirect ownership of it, we never call db.Close(). Ideally, that should be a defer call inside main(). We didn't do it properly before, but we still don't. I'm not sure how important it is to call db.Close() either (probably not that much, unless we're leaking resources and having processes die/restart all the time).

Maybe that's an argument for killing this entire file and moving the logic to `main.go` files everywhere? Thoughts?

Comment (RJPercival) [inline extension/builtin/default_registry.go]: I'm in favour of getting rid of what's left of this file and moving the logic to the various main.go files.

File: extension/builtin/default_registry.go (hunk 1 above)
Comment (RJPercival) [inline extension/builtin/default_registry.go]: Deleted entire `builtin` package.

File: server/trillian_log_server/main.go [hunk 4]
```diff
@@ -65,13 +68,16 @@ func main() {
 	glog.CopyStandardLogTo("WARNING")
 	glog.Info("**** Log RPC Server Starting ****")
 
-	registry := extension.Registry{
-		KeyProvider: keys.PEMKeyProvider{},
+	// First make sure we can access the database, quit if not
+	db, err := mysql.OpenDB(*mySQLURI)
+	if err != nil {
+		glog.Exitf("Failed to open MySQL database: %v", err)
 	}
```
Comment (codingllama) [inline server/trillian_log_server/main.go]: Add: `defer db.Close()`.

Same for others.

Comment (RJPercival) [inline server/trillian_log_server/main.go]: Done.

File: crypto/keys/pem_key_provider.go [hunk 5]
```diff
@@ -0,0 +1,35 @@
...
+	"fmt"
+
+	"github.com/golang/protobuf/ptypes"
+	"github.com/google/trillian"
+)
+
+// PEMKeyProvider loads PEM-encoded private keys.
+// It only supports trees whose PrivateKey field is a trillian.PEMKeyFile.
+// It implements keys.Provider.
+// TODO(robpercival): Should this cache loaded private keys? The SequenceManager will request a signer for each batch of leaves it sequences.
```
Comment (codingllama) [inline crypto/keys/pem_key_provider.go]: Suggestion: If that's only an issue for the sequencer, perhaps we should cache it there instead.

(No need to do any changes to the PR because of this comment.)

File: crypto/keys/pem_key_provider.go [hunk 6]
```diff
@@ -0,0 +1,35 @@
...
+type PEMKeyProvider struct{}
+
+// Signer returns a crypto.Signer for the given tree.
+func (p PEMKeyProvider) Signer(ctx context.Context, tree *trillian.Tree) (crypto.Signer, error) {
```
Comment (codingllama) [inline crypto/keys/pem_key_provider.go]: Could we have a test for this method?

File: testonly/integration/clientserver.go [hunk 7]
```diff
@@ -39,9 +41,21 @@ var (
 	sleepBetweenRuns = 100 * time.Millisecond
 	timeSource       = util.SystemTimeSource{}
 	// PublicKey returns the public key that verifies responses from this server.
-	PublicKey, _ = keys.NewFromPublicPEM(to.DemoPublicKey)
```
Comment (gdbelvin) [inline testonly/integration/clientserver.go]: This seems like we're adding some complexity here, do you think we can simplify it?

File: crypto/keys/pem_key_provider.go (hunk 6 above)
Comment (RJPercival) [inline crypto/keys/pem_key_provider.go]: Done.

File: crypto/keys/pem_key_provider_test.go [hunk 8]
```diff
@@ -0,0 +1,95 @@
+package keys
```
Comment (codingllama) [inline crypto/keys/pem_key_provider_test.go]: FYI, you're missing the license header.

Comment (daviddrysdale) [inline crypto/keys/pem_key_provider_test.go]: Hopefully Travis will also tell us that...

Comment (codingllama) [inline crypto/keys/pem_key_provider_test.go]: Yep, I'm watching it too.

Comment (RJPercival) [inline crypto/keys/pem_key_provider_test.go]: Strangely, Travis doesn't seem to have reported back.

Comment (RJPercival) [inline crypto/keys/pem_key_provider_test.go]: Fixed the missing license header.

File: testonly/integration/clientserver.go (hunk 7 above)
Comment (RJPercival) [inline testonly/integration/clientserver.go]: I've done a bit of refactoring, think that's any better?

File: crypto/keys/pem_key_provider_test.go (hunk 8 above)
Comment (codingllama) [inline crypto/keys/pem_key_provider_test.go]: Weird. I was concerned I might have caused a regression with #445 or #447, so I just deleted the license header on a file and ran presubmit locally, but it seems fine:

```bash
$ scripts/presubmit.sh ; echo "exit code = $?"
running golint
running go vet
running gocyclo
65 integration RunCTIntegrationForLog ./integration/ct_integration.go:67:1
running misspell
checking license header
Missing license header in: ./crypto/keys/pem_signer_factory_test.go
exit code = 5
```

Anyway, if you see anything strange happening (again) let me know.
