### PR TITLE
Client: Add QueueLeaf and WaitForInclusion. Fix flakey test

### LINKED ISSUE #659: client.TestUpdateRoot test is flaky
Recent failures:
 - https://travis-ci.org/google/trillian/jobs/240090210
```
--- FAIL: TestUpdateRoot (2.30s)
	client_test.go:263: Tree size after add Leaf: 0, want > 0
```
 - https://travis-ci.org/google/trillian/jobs/238419762
```
--- FAIL: TestUpdateRoot (1.29s)
	client_test.go:263: Tree size after add Leaf: 0, want > 0
```

### PR DESCRIPTION
**Pull request by gdbelvin**
In an attempt to fix flakey client tests, split AddLeaf into QueueLeaf
and WaitForInclusion.  This allows tests to manually run the sequencer
between these steps, removing a race condition.

Fixes #659

- Add explicit sequencing in tests
- Make client proxy more robust

### CODE REVIEW

**Comment by gdbelvin** [comment]
PTAL

File: client/client.go [hunk 1]
```diff
@@ -60,41 +64,25 @@ func (c *LogClient) Root() trillian.SignedLogRoot {
 }
 
 // AddLeaf adds leaf to the append only log.
-// Blocks until it gets a verifiable response.
+// If an entry is already present, it verifies it's inclusion proof,
```
Comment (daviddrysdale) [inline client/client.go]: it's => its

File: client/client.go [hunk 2]
```diff
@@ -214,6 +202,32 @@ func (c *LogClient) UpdateRoot(ctx context.Context) error {
 	return nil
 }
 
+// WaitForInclusion blocks until the requested data has been verified with an inclusion proof.
+func (c *LogClient) WaitForInclusion(ctx context.Context, data []byte) error {
+	leaf := c.logVerifier.buildLeaf(data)
+
+	// Fetch the current Root so we can detect .
```
Comment (daviddrysdale) [inline client/client.go]: so we can detect ... what?

File: client/client.go [hunk 3]
```diff
@@ -214,6 +202,32 @@ func (c *LogClient) UpdateRoot(ctx context.Context) error {
...
+		return err
+	}
+	err := c.getInclusionProof(ctx, leaf.MerkleLeafHash, c.root.TreeSize)
+	for {
+		if s, ok := status.FromError(err); !ok || s.Code() != codes.NotFound {
+			return err // Success or unexpected error.
+		}
+		if err := ctx.Err(); err != nil {
+			return err // Timeout.
+		}
```
Comment (daviddrysdale) [inline client/client.go]: I'm more used to a pattern like:
```go
	select {
	case <-ctx.Done():
		return ctx.Err()
	default:
	}
```
Do you know if there's an official preferred way to check for cancellation?

File: client/client.go [hunk 4]
```diff
@@ -214,6 +202,32 @@ func (c *LogClient) UpdateRoot(ctx context.Context) error {
 	return nil
 }
 
+// WaitForInclusion blocks until the requested data has been verified with an inclusion proof.
```
Comment (daviddrysdale) [inline client/client.go]: This function doesn't seem to be used or tested anywhere?

(Also, I'd have thought any possible users would probably already have a leaf in their hands, so maybe change the parameter to `leaf` not `data`)

File: client/client.go (hunk 1 above)
Comment (gdbelvin) [inline client/client.go]: Good point, reverted back to the original behavior.

File: client/client.go [hunk 5]
```diff
@@ -60,41 +64,25 @@ func (c *LogClient) Root() trillian.SignedLogRoot {
...
-
-			// Get proof by hash.
-			err = c.getInclusionProof(ctx, leaf.MerkleLeafHash, c.root.TreeSize)
+	}
+	if s.Code() == codes.AlreadyExists {
+		if err := c.UpdateRoot(ctx); err != nil {
+			return fmt.Errorf("UpdateRoot(): %v", err)
 		}
-		return err
+		if err := c.getInclusionProof(ctx, leaf.MerkleLeafHash, c.root.TreeSize); err != nil {
```
Comment (gdbelvin) [inline client/client.go]: Good question..  I've updated this to be `WaitForInclusion`

File: client/client.go (hunk 4 above)
Comment (gdbelvin) [inline client/client.go]: Added a test.

File: client/client.go (hunk 2 above)
Comment (gdbelvin) [inline client/client.go]: updated comment.

File: client/client.go (hunk 3 above)
Comment (gdbelvin) [inline client/client.go]: I think what you're recommending is more canonical. I'll switch to that.

**Comment by gdbelvin** [comment]
I've updated the PR, kept the original API behavior and added better tests. PTAL.

File: client/client.go (hunk 1 above)
Comment (gdbelvin) [inline client/client.go]: Good point. I'll keep the original API behavior.

**Comment by daviddrysdale** [comment]
The tests still look flaky -- do you want to investigate before I revisit?

**Comment by gdbelvin** [comment]
Should be stable now

File: client/client.go [hunk 6]
```diff
@@ -60,41 +59,16 @@ func (c *LogClient) Root() trillian.SignedLogRoot {
 }
 
 // AddLeaf adds leaf to the append only log.
-// Blocks until it gets a verifiable response.
+// If an entry is already present, it verifies its inclusion proof,
+// otherwise it returns immediately.
```
Comment (daviddrysdale) [inline client/client.go]: Comment doesn't seem accurate to current code.

File: client/client.go [hunk 7]
```diff
@@ -214,6 +188,36 @@ func (c *LogClient) UpdateRoot(ctx context.Context) error {
 	return nil
 }
 
+// WaitForInclusion blocks until the requested data has been verified with an inclusion proof.
```
Comment (daviddrysdale) [inline client/client.go]: Might be worth adding something like "This obviously assumes that the data has already been submitted (e.g. with QueueLeaf)." to the doc comment just to be clear.

File: client/client.go [hunk 8]
```diff
@@ -214,6 +188,36 @@ func (c *LogClient) UpdateRoot(ctx context.Context) error {
...
+func (c *LogClient) WaitForInclusion(ctx context.Context, data []byte) error {
+	leaf := c.logVerifier.buildLeaf(data)
+
+	// Fetch the current Root to improve our chances at a valid inclusion proof.
+	if err := c.UpdateRoot(ctx); err != nil {
+		return err
+	}
+	if c.root.TreeSize == 0 {
+		return fmt.Errorf("Tree is empty, TreeSize = 0")
```
Comment (daviddrysdale) [inline client/client.go]: Why is this necessarily an error?  What if you used `AddLeaf` to add the very first leaf to a log?

Comment (daviddrysdale) [inline client/client.go]: leading capital in error message

File: client/client.go [hunk 9]
```diff
@@ -214,6 +188,36 @@ func (c *LogClient) UpdateRoot(ctx context.Context) error {
...
+	}
+	err := c.getInclusionProof(ctx, leaf.MerkleLeafHash, c.root.TreeSize)
```
Comment (daviddrysdale) [inline client/client.go]: Wouldn't it be possible to move this down into the `for {` and drop the second copy?

File: client/client.go [hunk 10]
```diff
@@ -261,19 +265,16 @@ func (c *LogClient) getInclusionProof(ctx context.Context, leafHash []byte, tree
 	return nil
 }
 
-func (c *LogClient) queueLeaf(ctx context.Context, leaf *trillian.LogLeaf) error {
-	// Queue Leaf
-	req := trillian.QueueLeafRequest{
+// QueueLeaf add a leaf to a trillian log without blocking.
```
Comment (daviddrysdale) [inline client/client.go]: s/trillian/Trillian/

Comment (daviddrysdale) [inline client/client.go]: s/add/adds/

File: client/client.go [hunk 11]
```diff
@@ -261,19 +265,16 @@ func (c *LogClient) getInclusionProof(ctx context.Context, leafHash []byte, tree
...
+// AlreadyExists is considered a success case by this function.
+func (c *LogClient) QueueLeaf(ctx context.Context, data []byte) error {
```
Comment (daviddrysdale) [inline client/client.go]: This pull request adds 2 public entrypoints (`QueueLeaf`, `WaitForInclusion`), so the overall description is misleading.  (To put it another way, anyone hunting through commit logs trying to figure out when `QueueLeaf` was added is not going to spot this change.)

File: client/client_proxy.go [hunk 12]
```diff
@@ -53,24 +54,39 @@ func (c *MockLogClient) GetInclusionProof(ctx context.Context, in *trillian.GetI
 // GetInclusionProofByHash forwards requests.
```
Comment (daviddrysdale) [inline client/client_proxy.go]: (pre-existing) Comment is inaccurate -- the method does more than just forwarding requests

File: client/client_proxy.go [hunk 13]
```diff
@@ -15,6 +15,7 @@
 package client
 
 import (
+	"log"
```
Comment (daviddrysdale) [inline client/client_proxy.go]: We normally use `github.com/golang/glog` rather than `log`

File: client/client_proxy.go [hunk 14]
```diff
@@ -53,24 +54,39 @@ func (c *MockLogClient) GetInclusionProof(ctx context.Context, in *trillian.GetI
...
+	return resp, nil
 }
 
 // GetConsistencyProof forwards requests and modifies responses.
 func (c *MockLogClient) GetConsistencyProof(ctx context.Context, in *trillian.GetConsistencyProofRequest, opts ...grpc.CallOption) (*trillian.GetConsistencyProofResponse, error) {
 	resp, err := c.c.GetConsistencyProof(ctx, in)
+	if err != nil {
+		return nil, err
+	}
+	log.Printf("consistency: %v", resp.GetProof())
```
Comment (daviddrysdale) [inline client/client_proxy.go]: This is probably too spammy to leave in. Maybe `glog.V(2)` if you really want to keep it?

File: client/client_test.go [hunk 15]
```diff
@@ -193,32 +195,52 @@ func TestAddLeaf(t *testing.T) {
 	cli := trillian.NewTrillianLogClient(env.ClientConn)
 	for _, test := range []struct {
 		desc    string
+		leaf    []byte
 		client  trillian.TrillianLogClient
 		wantErr bool
```
Comment (daviddrysdale) [inline client/client_test.go]: `wantErr` unused -- preferably add an error test or two (e.g. use an invalid logID) rather than removing the field

File: client/client_test.go [hunk 16]
```diff
@@ -193,32 +195,52 @@ func TestAddLeaf(t *testing.T) {
 	cli := trillian.NewTrillianLogClient(env.ClientConn)
 	for _, test := range []struct {
 		desc    string
+		leaf    []byte
 		client  trillian.TrillianLogClient
```
Comment (daviddrysdale) [inline client/client_test.go]: with the current test data you could just drop the `client` member and use `cli`

File: client/client_test.go [hunk 17]
```diff
@@ -193,32 +195,52 @@ func TestAddLeaf(t *testing.T) {
...
-			wantErr: true,
-		},
+		{desc: "First leaf", leaf: []byte("A"), client: cli},
+		{desc: "Make TreeSize > 1", leaf: []byte("B"), client: cli},
 	} {
-		client := New(logID, test.client, testonly.Hasher, env.PublicKey)
-		err := client.AddLeaf(ctx, []byte(test.desc))
+		client := New(logID, test.client, rfc6962.DefaultHasher, env.PublicKey)
+		if err := client.QueueLeaf(ctx, test.leaf); err != nil {
+			t.Errorf("QueueLeaf(%v): %v", test.desc, err)
```
Comment (daviddrysdale) [inline client/client_test.go]: Could you put the `t.Errorf` message in canonical form please

File: client/client_test.go [hunk 18]
```diff
@@ -247,17 +269,17 @@ func TestUpdateRoot(t *testing.T) {
...
 	}
 
-	// Add the leaf without polling for inclusion.
-	leaf := client.buildLeaf([]byte("foo"))
-	if err := client.queueLeaf(ctx, leaf); err != nil {
-		t.Fatalf("queueLeaf('foo'): %v, want nil", err)
+	data := []byte("foo")
+	if err := client.QueueLeaf(ctx, data); err != nil {
+		t.Errorf("QueueLeaf(%s): %v, want nil", data, err)
+		return
```
Comment (daviddrysdale) [inline client/client_test.go]: why not `t.Fatalf` ?

File: client/client_test.go [hunk 19]
```diff
@@ -193,32 +195,52 @@ func TestAddLeaf(t *testing.T) {
...
+	for _, test := range []struct {
+		desc    string
+		leaf    []byte
+		client  trillian.TrillianLogClient
+		wantErr bool
+	}{
+		{desc: "First leaf", leaf: []byte("A"), client: cli},
+		{desc: "Make TreeSize > 1", leaf: []byte("B"), client: cli},
+		{desc: "invalid inclusion proof", leaf: []byte("A"), client: &MockLogClient{c: cli, mGetInclusionProof: true}, wantErr: true},
+	} {
```
Comment (daviddrysdale) [inline client/client_test.go]: (At the moment these tests completely subsume the ones in `TestQueueLeaf` so the latter could be dropped.  However, if you add some error cases above that will no longer be the case and you can ignore this comment.)

File: client/client.go (hunk 6 above)
Comment (gdbelvin) [inline client/client.go]: Thanks. Reverted back to original comment.

File: client/client.go (hunk 7 above)
Comment (gdbelvin) [inline client/client.go]: done

File: client/client.go (hunk 8 above)
Comment (gdbelvin) [inline client/client.go]: It's an error to request an inclusion proof with TreeSize == 0. 
I'll fix this to wait for a root update.

Comment (gdbelvin) [inline client/client.go]: removed.

File: client/client.go (hunk 9 above)
Comment (gdbelvin) [inline client/client.go]: done

File: client/client.go (hunk 10 above)
Comment (gdbelvin) [inline client/client.go]: done

Comment (gdbelvin) [inline client/client.go]: done

File: client/client.go (hunk 9 above)
Comment (gdbelvin) [inline client/client.go]: Question:  Currently requests for `TreeSize==0` returns `InvalidArgument`, which is technically correct, but I wonder if it would be more help to return `NotFound`?

File: client/client.go (hunk 11 above)
Comment (gdbelvin) [inline client/client.go]: I'll update the descriptions.

File: client/client_proxy.go (hunk 13 above)
Comment (gdbelvin) [inline client/client_proxy.go]: done

File: client/client_proxy.go (hunk 14 above)
Comment (gdbelvin) [inline client/client_proxy.go]: yep, accidentally left over. removed.

File: client/client_test.go (hunk 16 above)
Comment (gdbelvin) [inline client/client_test.go]: Good idea

File: client/client_test.go (hunk 15 above)
Comment (gdbelvin) [inline client/client_test.go]: QueueLeaf doesn't really have any if statements inside of it to test.  I wonder if I should just remove this test function?

File: client/client_test.go (hunk 17 above)
Comment (gdbelvin) [inline client/client_test.go]: added "want nil" -- is that clearer?

File: client/client_test.go (hunk 19 above)
Comment (gdbelvin) [inline client/client_test.go]: Agreed.  `TestQueueLeaf` is not really testing anything anymore.

File: client/client_test.go (hunk 18 above)
Comment (gdbelvin) [inline client/client_test.go]: Good point.

**Comment by gdbelvin** [comment]
Updated. PTAL

File: client/client.go [hunk 20]
```diff
@@ -214,6 +187,48 @@ func (c *LogClient) UpdateRoot(ctx context.Context) error {
...
+			case codes.OK:
+				return nil
+			case codes.NotFound:
+				// Wait for TreeSize to update.
+				if err := c.waitForRootUpdate(ctx); err != nil {
+					return err
+				}
+			default:
+				return err
+			}
```
Comment (daviddrysdale) [inline client/client.go]: I like the more explicit set of return cases -- much easier to follow.

One nitlet - is it possible to outdent this block by closing the `select` just after the `default` arm?

File: client/client_proxy.go [hunk 21]
```diff
@@ -50,27 +51,41 @@ func (c *MockLogClient) GetInclusionProof(ctx context.Context, in *trillian.GetI
...
-// GetInclusionProofByHash forwards requests.
+// GetInclusionProofByHash forwards requests and optionaly corrupts responses.
 func (c *MockLogClient) GetInclusionProofByHash(ctx context.Context, in *trillian.GetInclusionProofByHashRequest, opts ...grpc.CallOption) (*trillian.GetInclusionProofByHashResponse, error) {
 	resp, err := c.c.GetInclusionProofByHash(ctx, in)
+	if err != nil {
+		return nil, err
+	}
 	if c.mGetInclusionProof {
 		h := rand.Intn(len(resp.Proof))
+		if len(resp.GetProof()[h].Hashes) == 0 {
```
Comment (daviddrysdale) [inline client/client_proxy.go]: (nit) Stick to `resp.Proof` throughout for consistency (x 3)

File: client/client.go (hunk 20 above)
Comment (gdbelvin) [inline client/client.go]: Good idea. Done

File: client/client_proxy.go (hunk 21 above)
Comment (gdbelvin) [inline client/client_proxy.go]: done
