### PR TITLE
log: Restart election Runner in case of an error

### LINKED ISSUE #1150: If WaitForMastership fails log_signer sits around doing nothing
If the call to [`WaitForMastership` fails in `electionRunner.Run`](https://github.com/google/trillian/blob/a58c1a0253e92d7496de46a0950bd9b1ce128339/server/log_operation_manager.go#L150-L153) it returns from the function and sits around doing nothing for that log (i.e. `masterFor` calls will always return empty and nothing can be done). This can be triggered by recoverable intermittent etcd issues.

The `return` should either be replaced with `continue` (perhaps with a backoff?) when hitting errors from `WaitforMastership` or the `electionRunner` should be removed from `l.electionRunner[logID]` when it exits so a new election goroutine can be created the next time `masterFor` is called. I'd probably go for the first of the two options.

### PR DESCRIPTION
**Pull request by pavelkalinnikov**
This change makes the election/resignation loop restart indefinitely (with a reasonable
delay) in case it fails temporarily due to etcd issues.

Fixes #1150.

### Checklist

- [x] I have updated the [CHANGELOG](CHANGELOG.md).
  - Adjust the draft version number according to [semantic versioning](https://semver.org/) rules.
- [ ] I have updated [documentation](docs/) accordingly (including the [feature implementation matrix](docs/Feature_Implementation_Matrix.md)).

### CODE REVIEW

File: log/operation_manager.go [hunk 1]
```diff
@@ -256,25 +251,42 @@ func (o *OperationManager) masterFor(ctx context.Context, allIDs []int64) ([]int
...
-	e, err := o.info.Registry.ElectionFactory.NewElection(cctx, logID)
-	if err != nil {
-		cancel()
-		return nil, fmt.Errorf("failed to create election for %v: %v", logID, err)
-	}
-	o.runnerWG.Add(1)
-	go func() {
-		defer o.runnerWG.Done()
+	run := func(ctx context.Context) {
+		e, err := o.info.Registry.ElectionFactory.NewElection(ctx, logID)
```
Comment (Martin2112) [inline log/operation_manager.go:261]: Previously if the election was fundamentally broken these goroutines would return an error, now they'll loop.

We might need to look at adding metrics for election restart rate.

**Review by Martin2112 — APPROVED** [review]

File: log/operation_manager.go (hunk 1 above)
Comment (pavelkalinnikov) [reply log/operation_manager.go:261]: Agree.

I mitigated this in Migrillian by having a metric of restarts as you suggest, but instead of restarting only the election loop, I restarted the whole "operation" for this log. I think it will be a better granularity.

This will be easy to do if we restructure log operation as suggested in #1640, so that all the logs are nicely isolated (and only share some semaphores limiting the number of simultaneously running operations).

I'll add a TODO here.
