### PR TITLE
Reset flags in a cleaner way

### LINKED ISSUE #2364: Tests / presubmit fails under go 1.16
`go test ./...` fails under go 1.16, but works under go 1.15. The two tests that are failing are:

`github.com/google/trillian/cmd/updatetree`
`github.com/google/trillian/cmd/createtree`

Both fail with `panic: unexpected call to os.Exit(0) during test`, which looks to be a direct consequence of https://golang.org/doc/go1.16#go-test.

### PR DESCRIPTION
**Pull request by mhutchinson**
This avoids fiddling with the flag used by go's test framework, which fixes #2364 and means that the hack from #2365 can be removed.

### CODE REVIEW

File: scripts/presubmit.sh [hunk 1]
```diff
@@ -110,11 +108,6 @@ main() {
       TEST_FLAGS+=" -covermode=atomic -coverprofile=coverage.txt"
     fi
 
-    if [[ ${GOVER} -ge 16 ]]; then
-      # https://github.com/google/trillian/issues/2364
-      TEST_FLAGS_SUFFIX+=" -test.paniconexit0=false"
-    fi
-
     echo "running go test ${TEST_FLAGS} ./..."
     go test ${TEST_FLAGS} ./... ${TEST_FLAGS_SUFFIX}
```
Comment (pavelkalinnikov) [inline scripts/presubmit.sh:112]: Consider rolling this back to pre-#2365. The `TEST_FLAGS_SUFFIX` equals `-alsologtostderr` unconditionally.

**Review by pavelkalinnikov — APPROVED** [review]
