### PR TITLE
Require a PEM priv key password in CT frontend

### LINKED ISSUE #543: Standardize PEM password requirements
Per #532 `cmd/createtree` requires a password for the PEM priv key file or will fail out but `examples/ct/ct_server` does not.

Either require a password for both or neither.

### PR DESCRIPTION
**Pull request by rolandshoemaker**
Fixes #543.

### CODE REVIEW

**Comment by rolandshoemaker** [comment]
I guess it might also make sense to just to do this from `crypto/keys.NewFromPrivatePEMFile` so it doesn't accidentally drift out of sync again.

**Comment by codingllama** [comment]
Requiring a password at `keys.NewFromPrivatePEMFile` sounds good to me. It doesn't seem to break any tests either, so should be an easy change.

@RJPercival @Martin2112, any thoughts? For those without previous context in this discussion, the idea is to disallow unencrypted PEMs to be used with Trillian, with the intent to foster good practices.

**Comment by Martin2112** [comment]
If we do it this way we'll have to enforce it in each app. So I suspect it's better to do it in NewFromPrivatePEMFile. Rob?

**Comment by RJPercival** [comment]
Agreed, doing this in NewFromPrivatePEMFile seems best. All of our test keys are encrypted so that shouldn't cause any issues.

**Comment by codingllama** [comment]
Thanks, folks. Roland, you mind doing the fix here, instead of at *examples/ct/instance.go*? I'm happy to review it.

**Comment by rolandshoemaker** [comment]
Yup, will do.

File: crypto/keys/private.go [hunk 1]
```diff
@@ -38,8 +38,11 @@ type SignerFactory interface {
 }
 
 // NewFromPrivatePEMFile reads a PEM-encoded private key from a file.
-// The key may be protected by a password.
+// The key must be protected by a password.
 func NewFromPrivatePEMFile(keyFile, keyPassword string) (crypto.Signer, error) {
+	if keyPassword == "" {
+		return nil, errors.New("empty PEM key password")
```
Comment (RJPercival) [inline crypto/keys/private.go]: Could you include the `keyFile` value in the error message please, to make it obvious which file needs a password?

File: cmd/createtree/main.go [hunk 2]
```diff
@@ -147,9 +147,6 @@ func newPK(opts *createOpts) (*any.Any, error) {
 			return nil, fmt.Errorf("error reading PEM key file at %v: %v", path, err)
 		}
```
Comment (RJPercival) [inline cmd/createtree/main.go]: The code above that checks for existence of the PEM file needs to be deleted as well. This only works if the createtree command is run on the same machine as the Trillian server, since the file path is resolved by the server, not the client.

File: cmd/createtree/main.go [hunk 3]
```diff
@@ -139,20 +139,12 @@ func newRequest(opts *createOpts) (*trillian.CreateTreeRequest, error) {
...
 	case "PEMKeyFile":
-		path := opts.pemKeyPath
-		if path == "" {
+		if opts.pemKeyPath == "" {
 			return nil, errors.New("empty PEM path")
 		}
-		if _, err := os.Stat(path); err != nil {
-			return nil, fmt.Errorf("error reading PEM key file at %v: %v", path, err)
-		}
-		pass := opts.pemKeyPass
```
Comment (codingllama) [inline cmd/createtree/main.go]: nit: Since we've kept the `path != ""` validation, would you mind keeping the `pass != ""` check too, for consistency?

Both checks seem reasonable to keep, as they inform users of missing flags.

Comment (rolandshoemaker) [inline cmd/createtree/main.go]: Seems reasonable.

**Comment by rolandshoemaker** [comment]
Interesting: so it turns out that after #542 merged a few tests broke, mainly there is one that `os.Stat`'d a invalid path. Looking at `Server.CreateTree` doesn't actually need the private key in order to create a tree (since it doesn't actually sign the head).

If I completely don't initialized the `trillian.Tree` `PrivateKey` field everything seems to work as expected and tests pass. Any reason to not just carve all that extra code for reading the PEM file/pass out from `cmd/createtree`?

**Comment by codingllama** [comment]
Hey Roland, sorry for the slow turnover.

I thought we just did away with the `os.Stat` check (which I completely agree is for the best). Feel free to remove the `invalidPEMPath` test case from `cmd/createtree/main_test.go`. I'd like to keep the not empty checks for path/pass though, as they relate directly to mandatory flags that haven't been provided.

Just to clarify, as I may have misunderstood the comment, I fully expect the *real* CreateTree RPC to fail if a PEM is not provided; even though we don't do signing (yet), the server does attempt to create a Signer instead, for which the key needs to be read.

**Comment by rolandshoemaker** [comment]
Whoops, yup, somehow I missed the call to `trees.Signer` in `Server.CreateTree`, my bad!

**Comment by rolandshoemaker** [comment]
Done.
